version: '3.4'

services:
  covid19:
    image: covid19
    ports: 
      - 8501:8501
    networks:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.covid19.rule=Host(`covid19.robert-jensen.dk`)"
      - "traefik.http.routers.covid19.entrypoints=websecure"
      - "traefik.http.routers.covid19.tls=true"
      - "traefik.http.routers.covid19.tls.certresolver=myresolver"

networks:
  web:
    external: true
